### ISSUE TITLE
Can I do same work with Phantomx pincher arm ?

### ISSUE THREAD

**Issue by Abduoit** [JohnRoach/FollowMe#1]
Hi

I want to do the same project exactly, but I am using different robotic arm which is Phantomx Pincher robotic arm which has 5 DOF. 

Can I ask you please ? 
do you need to do calibration to the webcam ? 
can the arm follow the red object in 3d dimensions x, y and z. Or only x and y ?

How can I use it with my robotic arm ??

**Comment by johnroach** [comment]
Calibration for the webcam is not needed. What you need is to make sure you create a control mechanism. Check out the https://github.com/HumaRobotics/phantomx_gazebo for sample python code. That is all I know about Phantomx. Have fun!
